Repository gerardowacker/rar.vg, pull requests merged in 2023-10, with the labels that each got.

#28 Added `YouTubeComponent`
  src/components/editableprofile.component.js
  src/components/editpanel.component.css
  src/components/editpanel.component.js
  src/components/youtube.component.js
  src/pages/profile.js
Labels: size/L

#27 Added Spotify component
  src/components/editableprofile.component.js
  src/components/editpanel.component.js
  src/components/spotify.component.js
  src/pages/profile.js
Labels: size/M

#26 Change the border color of the list button
  src/components/editpanel.component.css
Labels: size/S
