Repository gerardowacker/rar.vg, pull requests merged in 2025-09, with the labels that each got.

#38 Added notification message
  src/pages/dashboard.css
  src/pages/dashboard.js
Labels: size/XL

#39 Now added CTRL + Shift + Z funcionality. Does the same as CTRL + Y
  src/pages/dashboard.js
Labels: size/S

#40 Separated EditPanel into different panels
  src/components/editpanel.component.js
  src/components/panels/generic.panel.component.js
  src/components/panels/linklist.panel.component.js
  src/components/panels/pdf.panel.component.js
  src/components/panels/sociallinks.panel.component.js
  src/components/panels/spotify.panel.component.js
  src/components/panels/user.panel.component.js
  src/components/panels/youtube.panel.component.js
  src/pages/dashboard.js
Labels: size/XXL
